apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-secret
  labels:
{{ include "myapp.labels" . | indent 4 }}
type: Opaque
data:
  secret.txt: "{{ .Files.Get "secret.txt" | b64enc }}"
