---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tiller
  namespace: myapp-staging
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-tiller
  namespace: myapp-staging
subjects:
- kind: ServiceAccount
  name: default
  namespace: myapp-staging
roleRef:
  kind: Role
  name: tiller
  apiGroup: rbac.authorization.k8s.io
