# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1
image:
  repository: registry.default.svc:80/apps/myapp
  tag: stable
  pullPolicy: Always
