apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test

spec:
  containers:
    - name: testcontainer
      image: alpine
      command:
        - sh
        - -c
        - echo Hallo Welt && sleep 3600
    - name: test2
      image: busybox
      command:
        - nc
        - -l
        - 127.0.0.1
        - -p
        - "1337"
